aragon/ui

package-lock.json
package.json
yarn.lock

Using `npm run optimize:svg` so we can add other `npm run optimize:something` later, and run everything with `npm run optimize`.

Add npm script to optimize SVG files

---

README.md

As discovered in https://github.com/aragon/aragon-apps/pull/42

Add syncing instructions for create-react-app or react-scripts users

---

src/shared-styles.js

Springs: make “fast” less bouncy

---

src/components/Button/Button.js

Adds flow types to Button's props.

Button: add flowtypes

---

gallery/src/App.js

Fixes #64.
Noticed it wasn't showing up in https://github.com/aragon/aragon/pull/74/; nice one @bpierre!

Gallery: fix content overflowing

---

src/components/AragonApp/AppBar.js
src/components/DropDown/DropDown.js
src/theme/Aragon.oco
src/theme/aragon.json

Various changes required by the “Permissions app” PR of Aragon: https://github.com/aragon/aragon/pull/76

Permissions changes

---

src/theme/Aragon.oco
src/theme/aragon.json

Make `contentBorder` lighter to get closer to the Sketch files.

Theme Colors: make contentBorder lighter

---

gallery/src/App.js
gallery/src/components/Page/DemoContainer.js
gallery/src/pages/PageAppBar.js
gallery/src/pages/PageAragonApp.js
gallery/src/pages/PageButton.js
gallery/src/pages/PageCard.js
gallery/src/pages/PageCircleGraph.js
gallery/src/pages/PageDropDown.js
gallery/src/pages/PageEmptyStateCard.js
gallery/src/pages/PageField.js
gallery/src/pages/PageSidePanel.js
gallery/src/pages/PageTable.js
gallery/src/pages/PageTextInput.js
src/components/AragonApp/AppBar.js
src/components/AragonApp/AppBar.md
src/components/AragonApp/AragonApp.md
src/components/Button/README.md
src/components/Card/Card.md
src/components/Card/EmptyStateCard.md
src/components/Field/README.md
src/components/SidePanel/README.md
src/components/SidePanel/SidePanel.js
src/components/Table/Table.md

This adds documentation for the components listed in #6. The copy may need a little tweaking to your preference, but the bulk of the work is completed in this PR. Fixes #6

Implement missing components documentation

---

src/components/BadgeNumber/BadgeNumber.js

Add a way to customize the background and text colors.

BadgeNumber: background and color props

---

gallery/src/pages/PageField.js
src/components/Field/Field.js
src/components/Input/TextInput.js
src/components/Input/TextInput.md

I am not sure about how to show the new feature in gallery but you guys can give me a hint.
I am also a bit uneasy with the float rule that I wrote, open to suggestions on how to make this better.
resolves: #87

add required asterix in Field component

---

.eslintignore
.eslintrc
package-lock.json
yarn.lock

Now imports will throw linter errors if they don't exist (among other nice things<sup>TM</sup>)

Add eslint-plugin-import

---

gallery/src/App.js
gallery/webpack.config.js

Fix the fonts in development mode.

Gallery: dynamic publicPath for Aragon UI

---

src/components/SidePanel/SidePanel.js

Scrollable SidePanel 🎊
<p align=center>
</p>

SidePanel: add a scrollable view

---

gallery/src/pages/PageIcons.js
gallery/src/routes.js

Depends on https://github.com/aragon/aragon-ui/pull/125

Gallery: add a page to visualize the icons

---

package.json

According to https://github.com/aragon/aragon-ui/blob/master/LICENSE

License should be MIT, fix 134

---

gallery/package.json
gallery/src/App.js
gallery/yarn.lock
src/components/AragonApp/AragonApp.js
src/components/BaseStyles/BaseStyles.js

For now, it adds .woff files in addition to the .woff2 files.

Add a supportLegacyAgents prop to AragonApp

---

gallery/src/pages/PageRedraw.js
gallery/src/pages/PageRedrawFromDate.js
gallery/src/routes.js

To be merged before https://github.com/aragon/aragon-ui/pull/158

Gallery: add PageRedraw / PageRedrawFromDate pages

---

src/components/BaseStyles/BaseStyles.js
src/components/Input/TextInput.js

Add TextInput.Multiline (textarea element)

---

src/components/AragonApp/AppView.js

Also makes the top bar always on top.

AppView: use 100% of the viewport height

---

src/components/Slider/Slider.js

That way, the handle can never be on a different position than the active bar.
Caching the rectangle has also been disabled, because there is no way to know if the geometry is up to date when the value is updated from the outside.

Slider: don’t rely on the rectangle to position the handle

---

src/components/AragonApp/AppView.js

AppView: remove the AppBar type check

---

gallery/src/pages/PageRadioButton.js
src/components/Input/RadioButton.js
src/components/Radio/RadioListItem.js

RadioButton: styling tweaks

---

devbox/index.js

The app is now set using the DEVBOX_APP environment variable.
Example:
```
DEVBOX_APP=Button npm start
```

devbox: select the app to run from the CLI

---

src/components/IdentityBadge/IdentityBadge.js
src/utils/web3.js

This is temporary (so we can use the badge everywhere) and will be replaced by the Popover when ready.

IdentityBadge: open etherscan when clicked

---

src/components/IdentityBadge/IdentityBadge.js
src/utils/web3.js

IdentityBadge: fix network type

---

src/components/SidePanel/SidePanel.js

SidePanel content: prevent shrinking

---

gallery/src/components/Page/DemoContainer.js
gallery/src/components/Page/Frame.js
gallery/src/pages/PageDropDown.js
gallery/src/pages/PageNavigationBar.js
gallery/src/pages/PageRadioButton.js
gallery/src/pages/PageRadioGroup.js

Based on the react-spring-6 branch, to be merged in master after #244 is merged.

Gallery tweaks

---

devbox/index.js

Not using the UI toolkit on purpose, to differentiate the index from the actual demos.

devbox: demos index

---

src/components/BaseStyles/BaseStyles.js

By setting the `fontFamily` prop.
Related to https://github.com/aragon/aragon/issues/490

BaseStyles: make it possible to change the default font

---

devbox/index.html
devbox/index.js
devbox/package.json
devbox/webpack.config.js

On my laptop, it makes the build twice as fast, and live reload works.

devbox: move from parcel to webpack

---

gallery/src/pages/PageRadio.js
gallery/src/pages/PageRadioGroup.js
gallery/src/pages/PageRadioList.js
src/components/Input/Checkbox.js
src/components/Input/Radio.js
src/components/Input/Radio.md
src/components/Radio/RadioGroup.js
src/components/Radio/RadioGroup.md
src/components/Radio/RadioList.js
src/components/Radio/RadioList.md
src/components/Radio/RadioListItem.js

Fixes the documentation and gallery, and refactors the `RadioList` to be based on the new implementation.

Changes for RadioButton + RadioGroup update

---

src/components/SidePanel/SidePanel.js

Responsive SidePanel component

---

.babelrc
package-lock.json
package.json
rollup.config.js

Makes `Toast` / `ToastHub` work even when `@babel/polyfill` is not present.

Add @babel/runtime (await / async support)

---

src/components/Input/TextInput.js

To align it with the `DropDown` and `Button` components.

TextInput: move to a fixed height: 40px

---

src/components/BaseStyles/BaseStyles.js
src/theme/Aragon.oco
src/theme/aragon.json

Add a selection style

---

devbox/apps/Scratchpad.js
devbox/index.js

Easier than creating an app every time we want to test something.

devbox: add an empty app for temporary things

---

devbox/apps/TabBar.js
gallery/src/pages/PageTabBar.js
gallery/src/routes.js
src/components/TabBar/README.md
src/components/TabBar/TabBar.js

Also add documentation and move to `React.createRef()`.

TabBar: rename onSelect to onChange

---

src/components/FocusVisible/FocusVisible.js
src/components/IdentityBadge/IdentityBadge.js

- Fix the vertical alignment of IdentityBadge ([again](https://github.com/aragon/aragon-ui/pull/307)!).
- Ensure to always remove the `<span>` used to get the current document in `FocusVisible`.

IdentityBadge alignment fix

---

README.md
bin/copy-aragon-ui-assets
src/components/Main/Main.js
src/components/Main/README.md
src/providers/PublicUrl/PublicUrl.js

Related discussion: https://github.com/aragon/aragon-apps/pull/692

Main: relative assets url

---

devbox/apps/NavigationBar.js
devbox/package.json
gallery/src/pages/PageNavigationBar.js
src/components/NavigationBar/NavigationBar.js
src/components/NavigationBar/README.md

This change keeps the alignments in sync for small screens.

NavigationBar: update spacing + add documentation

---

README.md

README: new aragonUI brand

---

src/components/IdentityBadge/IdentityBadge.js
src/components/IdentityBadge/IdentityBadgePopover.js
src/components/IdentityBadge/PopoverActionType.js

The modal is as raw as it can get:

Identity badge custom label action

---

src/components/Modal/Modal.js
src/components/Modal/README.md

- Allow to pass the overlay color.
- Fix the z-index.

Modal fixes

---

src/components/Modal/Modal.js
src/components/Modal/README.md

- `radius` prop
- use drop-shadow()

Modal radius

---

src/components/FocusVisible/FocusVisible.js

During a crash, prevent the “document is undefined” messages to appear in lieu of the actual error.

Fix “document is undefined” errors

---

src/components/ToastHub/ToastHub.js

Prevent ToastHub to re-render its own tree if only `children` changes.

ToastHub: skip extra renderings

---

src/components/IdentityBadge/IdentityBadgePopover.js
src/utils/web3.js

Fixes #367 
The `IdentityBadge` without a link:

feat: Enhance blockexplorer url

---

src/components/IdentityBadge/IdentityBadge.js

If the badgeOnly prop is set to true, the IdentityBadge will not have an `on click` behavior and will not display the IdentityBadgePopover

IdentityBadge: badgeOnly prop 

---

src/hooks/useImageExists.js

Easiest to review this commit only https://github.com/aragon/aragon-ui/commit/affbfe037422d22b9440b366a252d871530e10c3, the other one is cosmetic.

useImageExists() initial state

---

gallery/src/pages/PagePopover.js
src/components/Popover/README.md

Fixes #396
Just repeating the pattern used in the `devbox` which rendered the component as intended.

Fix popover inside gallery

---

src/components/Bar/Bar.js

- Let the content overflow.
- Pass extra props.

Bar: let the content overflow + pass extra props

---

src/components/DropDown/DropDown.js
src/components/ProgressBar/ProgressBar.js
src/utils/environment.js

Makes it easier to warn about deprecated things :hugs:

Add warnOnce()

---

src/components/DropDown/DropDown.js

Dropdown fix

---

devbox/apps/DataView.js
src/components/DataView/DataView.js

Related to https://github.com/aragon/aragon-apps/pull/918#issuecomment-520197524

 DataView: fix the alignment of a single field 

---

src/components/DropDown/DropDown.js

Changes:
- Fix height.
- Vertically center the menu.
- Prefer `selected` over `active`.
- naming + hook dependencies fixes.

Dropdown tweaks

---

src/components/Button/Button.js

Button: fix min-width

---

src/components/Field/Field.js
src/components/Field/README.md

Useful when the children are complex, e.g. when it has to render more than one child.

Field: add way to force required mode

---

src/theme/aragon-colors.js
src/theme/theme-dark.js
src/theme/theme-light.js

Colour naming to be finalized cc @owisixseven.

Theme: add hint color

---

src/components/SidePanel/SidePanel.js

- Move to `css`.
- Indentation / formatting.
- Fix the overlay color.
- Fix the shadow color.

Sidepanel tweaks

---

src/components/DropDown/DropDown.js

From https://github.com/aragon/aragon-ui/pull/488/files/84153cd729d7fda394d3b034e78ef49fc81170d1#r315057316.

DropDown: small styling clean up

---

src/components/ContextMenu/ContextMenu.js

🙈 Tried to get smart and simplify the z-index switching, this puts that bit of logic back in with a comment explaining why it's necessary.

ContextMenu: fix z-index when opening menu

---

src/components/Header/Header.js

<p align=center><img src=https://user-images.githubusercontent.com/36158/63390730-6359ca00-c3b0-11e9-95db-49981aae220d.png width=50%>

Header: prevent text overflow / wrap

---

devbox/apps/Tag.js
src/components/Tag/Tag.js

Like `IdentityBadge` does:
<p align=center><img width=200 src=https://user-images.githubusercontent.com/36158/63382171-75c90900-c39a-11e9-8e77-51d3635c2f76.png></p>

Tag: prevent the label to overflow

---

devbox/apps/DataView.js
src/components/DataView/DataView.js
src/components/DataView/README.md

Allows the selection to be controlled from the outside.

DataView: add the selection prop

---

gallery/src/pages/PageTable.js
src/components/Table/Table.js
src/components/Table/TableCell.js
src/components/Table/TableHeader.js

Table: new style update: useTheme() + GU

---

devbox/apps/Wrappers.js
src/components/Card/Card.js

To make the keyboard activation work.
@AquiGorka Thanks for suggesting this! I couldn’t notice any change in the cards layout for Permissions, Voting, or App Center, so it seems to be working just fine.

Card: use ButtonBase when interactive

---

devbox/apps/DataView.js
src/components/DataView/DataView.js
src/components/DataView/ListView.js
src/components/DataView/README.md
src/components/DataView/TableView.js

@sembrestels @deamme let me know if it does the job for the conviction voting app! :smile:

DataView child content: dynamic height + rename it to “expansion”

---

src/components/DateRange/DateRange.js

DateRange: toggle open and change cursor to pointer

---

src/components/ButtonBase/ButtonBase.js
src/components/Card/Card.js
src/utils/keycodes.js

Move to an inner `<div>` element to avoid any layout specificity with `<button>`.

Card: fix the layout differences in interactive mode

---

src/components/DateRange/DatePicker.js
src/components/DateRange/DateRange.js

🙈 Oops, the current DateRange doesn't allow anyone to actually pick a date.
This is a bit of a stop-gap measure to fix this for now.

DateRange: avoid closing early when clicking inside its opened state

---

src/components/Card/Card.js

Added by mistake in https://github.com/aragon/aragon-ui/pull/541

Card: remove the border

---

src/components/AutoComplete/AutoComplete.js
src/components/AutoComplete/AutoCompleteSelected.js

Updates the AutoComplete component in various ways to make its styling and handling behaviour more consistent with other similar components (e.g. DropDown, etc.).

AutoComplete: newstyle

---

src/components/Tag/Tag.js

Ref: https://github.com/aragon/aragon-ui/issues/552

Tag: remove cast to string

---

devbox/apps/IdentityBadge.js
devbox/apps/TokenBadge.js
src/components/BadgeBase/BadgeBase.js
src/components/BadgeBase/BadgePopoverActionType.js
src/components/BadgeBase/BadgePopoverBase.js
src/components/IdentityBadge/IdentityBadge.js
src/components/IdentityBadge/IdentityBadgePopover.js
src/components/IdentityBadge/PopoverActionType.js
src/components/IdentityBadge/README.md
src/components/TokenBadge/TokenBadge.js
src/components/TokenBadge/TokenBadgePopover.js
src/components/TransactionBadge/README.md
src/components/TransactionBadge/TransactionBadge.js

@bpierre What do you think about consolidating all of IdentityBadge, TokenBadge, TransactionBadge, and AppBadge via this BadgeBase? It's really an internal component that sets up the base styling and behaviours for each Badge component so they don't have to do as much themselves.
The name conflicts a bit with the deprecated Badge, but I think this is OK (users should think of that as Tags now).

Add BadgeBase

---

src/theme/aragon-colors.js
src/theme/theme-dark.js
src/theme/theme-light.js

- Fix ArcticBlueDarker (and `theme.hint`).
- Update disabled colors.
- Update `surfaceIcon`.

Update theme + colors

---

src/components/AppBadge/AppBadge.js

AppBadge: rename internal variable names to be AppBadge

---

src/components/DataView/DataView.js
src/components/DataView/README.md

Fixes https://github.com/aragon/aragon-ui/issues/593

DataView: reset managed pagination on entries change

---

devbox/apps/Input.js
src/components/Input/SearchInput.js
src/components/Input/SearchInput.md
src/components/index.js

Search input component

---

src/theme/theme-dark.js
src/theme/theme-light.js

Update controls colors and add `controlDisabled` color in theme

Theme: update colors

---

README.md

README: add missing parts into the quick setup

---

ThemePalette.md

Describes every color used by the theming system.
/cc @delfipolito

Add documentation about the palette used in the themes

---

src/components/Radio/RadioList.js
src/components/Radio/RadioListItem.js
src/components/TransactionProgress/TransactionProgress.js

See https://github.com/aragon/aragon-ui/pull/625#discussion_r337624457

GU syntax fixes (coding style)

---

src/components/Tabs/Tab.js
src/components/Tabs/Tabs.js

- Remove the hover effect.
- Add a pressed effect.
- Use ButtonBase for the onClick behavior and focus state.

Tabs: activate on release + remove hover

---

src/components/AddressField/AddressField.js
src/components/AddressField/README.md

Allows to disable this behavior when needed.

AddressField: add the autofocus prop

---

ThemePalette.md
src/components/Tag/Tag.js
src/theme/theme-dark.js
src/theme/theme-light.js

- First pass at the dark theme colors.
- Add controlSurface and selectedDisabled colors.
- Remove transparency for some colors of the `Tag` component.

Theme update

---

src/components/Input/Checkbox.js
src/components/Input/Checkbox.md
src/components/Input/Radio.js
src/components/Input/Radio.md

Checkbox + Radio: add a disabled state

---

src/components/Switch/Switch.js

- Remove the handle shadow when disabled.
- Use different theme colors for the handle and the disabled state.
- Coding style / formatting.

Switch: styling tweaks

---

devbox/apps/Checkbox.js
devbox/apps/Everything.js
devbox/apps/Info.js
devbox/apps/Radio.js
devbox/apps/Switch.js
devbox/components/SplitSurfaces.js

- Visually align Checkbox / Radio / Switch demos.
- Add a SplitSurfaces component, to visualize how a component behaves on both
theme.background and theme.surface.
- Various updates.

devbox: align Checkbox + Radio + Switch

---

src/components/Input/Checkbox.js

Checkbox + Radio: update dimensions

---

src/components/Info/Info.js
src/theme/theme-dark.js
src/theme/theme-light.js

- Remove transparency on `Info` and update colors accordingly.
- Update `Tag` colors.

Update Info + Tag colors

---

devbox/apps/AddressField.js
src/components/AddressField/AddressField.js
src/components/AppBadge/AppBadgePopover.js
src/components/TextCopy/TextCopy.js
src/components/TokenBadge/TokenBadgePopover.js
src/components/index.js

-  AddressField: restore support for icon (accidentally removed in https://github.com/aragon/aragon-ui/pull/612).
- TextCopy: fix icon alignment (for custom icons).
- TokenBadgePopover: remove unnecessary container.
- Coding style.

Various badge fixes

---

scripts/generate-icons

Just a cosmetic change to remove the wall of icon names :laughing:

Better output for the icons:build task

---

gallery/src/pages/PageDateRangePicker.js

- Solve the DateRangePicker bug with the iframe container by removing it; Same as #670 
- Improved demo to match example implementation with the addition of state for being able to select dates.

Solve DateRangePicker container bug, improve demo

---

gallery/webpack.config.js
package.json

Also updates the gh-pages module.

Gallery: create the /help directory

---

src/proptypes.js

PropType functions should return `null` or an error, not `true`.

Fix PropTypes._element

---

src/components/EscapeOutside/EscapeOutside.js

EscapeOutside: mark onEscapeOutside prop as required

---

devbox/apps/DataView.js
src/components/DataView/TableView.js
src/components/index.js

Accordion: Always display border for expanded content

---

src/components/Tabs/TabsFullWidth.js

@bpierre not sure wich color use for the icon disabled since the `theme.disabledIcon` is the same color than `theme.surfaceIcon` both have `#8FA4B5` so i just used `theme.disabled`
this closes #595

Tabs: improve full width mode

---

src/utils/format.js
src/utils/format.test.js
src/utils/math.js
src/utils/math.test.js

This PR is to address @sohkai’s comments in https://github.com/aragon/aragon-ui/pull/728.

formatTokenAmount() updates

---

README.md
devbox/package.json
devbox/scripts/check-link
devbox/scripts/update-apps-index
devbox/yarn.lock

See https://github.com/aragon/aragon-ui/issues/731#issuecomment-596145523 (should we close it for this?).
Updates the README and adds a warning when starting the devbox if `@aragon/ui` isn't linked.

devbox: update instructions

---

src/components/LoadingRing/README.md

Docs: Fix typo on LoadingRing documentation

---

devbox/apps/Modal.js
src/components/Modal/Modal.js
src/components/Modal/README.md

resolves https://github.com/aragon/aragon-ui/issues/791

Modal: Provide onClosed callback

---

package.json

I forgot to push this yesterday 😬

gh-pages: include the .nojekyll file

---

src/components/DataView/TableView.js

This is an alternative approach to https://github.com/aragon/aragon-ui/pull/810 without relying on spring to handle auto. This is superior in some ways because values always remain accurate and up to date, transitions are also preserved when reordering.
Only drawback is that the height of the expansion it remeasured more often than is needed (while it's open) but without changing the api we have no reliable and unique information to use as dependencies other than the content nodes (which could arguably be more expensive and more complex to compare)

DataView: Explicit auto over spring internals

---

devbox/apps/Input.js
src/components/Input/SearchInput.js
src/components/Input/TextInput.js

- remove input adornment border
- change search input adornment position

feature / DAO-324 
