aragon/ui

- gallery/src/App.js
- gallery/src/pages/PageButton.js
- gallery/src/pages/PageDropDown.js
- gallery/src/pages/PageFooter.js
- gallery/src/pages/PageHeader.js
- gallery/src/pages/PageIllustratedSection.js
- gallery/src/pages/PagePreFooter.js
- gallery/src/pages/PageSection.js
- gallery/src/pages/PageText.js
- gallery/src/pages/PageTheme.js
- gallery/webpack.config.js
- package-lock.json
- package.json
- rollup.config.js
- src/components/AragonApp/AragonApp.js
- src/components/BaseStyles/BaseStyles.js
- src/components/Button/Button.js
- src/components/DropDown/DropDown.js
- src/components/Footer/Footer.js
- src/components/Header/Logo.js
- src/components/Header/MenuPanel.js
- src/components/PreFooter/PreFooter.js
- src/components/Section/Section.js
- src/index.js
- src/public-url.js
- src/shared-styles.js
- yarn.lock
There are two different ways to handle a library as a dependency:
- As a source library
- As a runtime library, transpiled to “universal JS”
The problem with the source is that it brings many problems to make it work with the parent app:
- Having to install the same dependencies in the parent project.
- Having to install the same build dependencies.
- Having to configure the build exactly the same way.
- Update these every time the library is updated.
Using the transpiled library solves all this problems, except one. Most modern build systems have some mechanism to import non-JS dependencies, which allows, in the context of a components library, to have the assets of a component in the same directory (instead of using a global folder).
When the modules are transpiled, the link between the …
> Set the assets public URL at runtime

- .babelrc
- gallery/package.json
- gallery/webpack.config.js
- gallery/yarn.lock
- package-lock.json
- package.json
- yarn.lock
See the [styled-component docs](https://www.styled-components.com/docs/tooling#babel-plugin).
Provides a small debugging quality-of-life upgrade in the gallery for component names and classnames.
I've left the plugin's own minification and transpilation step on since they seem fairly safe. They're producing a negligible ~3-4kb decrease on the non-minified builds for me right now.
> Add babel-plugin-styled-components

- src/components/DropDown/DropDown.js
- src/components/DropDown/DropDownItem.js
Rendering the `StyledDropDownItem` as a `<div>` rather than a `<li>` seems unnecessary... maybe I'm missing something?
> DropDownItem: render DropDownItem as a <li>

- package.json
Having the `viewBox` attribute removed prevent scaling SVG images. This PR tells svgo to preserve this attribute.
See the discussion in https://github.com/aragon/aragon-ui/pull/28
> Change the optimize:svg task to preserve the viewBox attribute

- src/components/BadgeNumber/BadgeNumber.js
- src/index.js
- src/theme/Aragon.oco
- src/theme/aragon.json
Depends on https://github.com/aragon/aragon-ui/pull/33.
This PR adds a `<BadgeNumber />` component:
It can be used to indicate the available notifications and other things (updates, messages, etc.). Its color is `theme.positive` for now, that could evolve in the future.
Maybe we could also provide something to help positioning it on top of an icon, like this:
We could add a property to icon components?
```jsx
<IconWallet badgeNumber={7} />
```
But we might want to position it on top of other things than icons.
Or by having an wrapping component:
```jsx
<BadgeNumber.Attacher>
<IconWallet />
<BadgeNumber number={7} />
</BadgeNumber.Attacher>
```
Or by considering that app authors can position it themselves.
Any thoughts?
> BadgeNumber

- src/components/SidePanel/SidePanel.js
Oops, missed that `styledPublicUrl()` is a HOF meant to be used with `css()`.
Fixes SidePanel so that its close button's img src is built with `prefixUrl()` instead.
> SidePanel: fix close button's src pathing

- src/components/DropDown/DropDown.js
- src/components/DropDown/DropDownItem.js
- src/components/DropDown/README.md
A few fixes for the DropDown component:
- Use `role` attributes to make the component more accessible by screen readers.
- Revert back to use `<div>` for DropDownItem (the item is also used outside of `<ul>`).
- Default height when the component is empty (so that it doesn’t look broken).
- Fix a typo in the README.
- Add a `wide` property.
> Dropdown fixes

- .babelrc
Enables display names for users of this component library.
Increases the build size by ~2-3kb, which I think is OK for now given the quality of life upgrade. In the future, we can have a production build where this is turned off, or perhaps even better, change the plugin so that all the display names are under a `NODE_ENV` flag.
> Show display names of styled components in builds

- gallery/src/render-readme.js
- package.json
- yarn.lock
Adds `id=<header-title>` attributes to h2 and h3 headers parsed from each component's readme.
Useful for intra-document linking, e.g. to reference a specific property or group from another part of the same document. Doesn't work for permalinking, due to the way routing is handled in the gallery.
> Gallery: add markdown-it-anchor

- gallery/package.json
- gallery/yarn.lock
- package.json
- yarn.lock
I have no idea how this was working locally before... but now `markdown-it-anchor` is properly installed in the gallery.
> Fix installation of markdown-it-anchor

- gallery/src/pages/PageButton.js
- gallery/yarn.lock
- src/components/Button/Button.js
- src/components/Button/README.md
- src/components/Card/EmptyStateCard.js
Required for https://github.com/aragon/aragon/issues/66.
Maybe not the most "component"y (it'd be nice if people didn't have to care about `<a>`s and `Button`s exposed a linking API that didn't reinvent the wheel), but certainly the simplest.
Adds a demo to the gallery:
> Add Button.Anchor

- gallery/src/pages/PageText.js
- src/components/AragonApp/AppBar.js
- src/components/Card/EmptyStateCard.js
- src/components/Field/Field.js
- src/components/Header/Header.js
- src/components/SidePanel/SidePanel.js
- src/components/Table/TableHeader.js
- src/components/Text/README.md
- src/components/Text/Text.js
Refactors `Text` to be more similar to `Button` (i.e. no element-switching).
> Text: refactor to always render as <span>

- src/components/Card/EmptyStateCard.js
Makes it easier to use `EmptyStateCard` in apps, who might want to supply their own button (e.g. an anchor) and a non-local static asset for the icon.
> EmptyStateCard: generalize input components

- gallery/src/pages/PageButton.js
- src/components/Button/Button.js
- src/components/Button/README.md
Required for the [voting app (see bottom button)](https://scene.zeplin.io/project/59a827960d4c4cb2274007f5/screen/59a82800d913ba794a4a5b4a).
> Button: add secondary mode

- src/components/SidePanel/SidePanel.js
Avoids the outline when focused:
> SidePanel: remove outline and selectable from close button

- src/components/SidePanel/SidePanel.js
Some changes on the `SidePanel` component:
- The panel can now be closed using a click on the overlay, or the Escape key.
- A new prop, `blocking`, has been added. When set to `true`, the `onClose` event won’t be invoked, and the close button won’t appear at all. Defaults to `false`.
- The overlay used to prevent clicks until the closing transition is 100% finished. Clicks through the overlay now work as soon as the transition starts.
- Flow has been replaced by `prop-types`.
- The entire header is now unselectable.
> SidePanel updates (blocking prop)

- src/components/Table/TableCell.js
- src/components/Table/TableHeader.js
Add support for `align` on `TableCell` and `TableHeader`.
Also removes references to flow.
> TableCell / TableHeader: support align

- src/components/Button/Button.js
- src/components/Button/assets/check-white.svg
- src/components/Button/assets/cross-white.svg
> Button: support for emphasis + strong mode

- src/components/SidePanel/SidePanel.js
Some additions to the SidePanel component:
1. Export the dimensions − useful to position inner components.
2. Add a `onTransitionEnd` callback − useful to update inner components after the panel opens or closes.
> SidePanel update

- src/components/PreFooter/PreFooter.js
The website's version of aragon-ui doesn't seem to have this problem.
Anyhow, React will complain since the default email form isn't invoked as a component and not show it:
> PreFooter: invoke default email form as component

- src/components/AragonApp/AppBar.js
- src/components/DropDown/DropDown.js
From discussion in #79.
Always invoke argument-less functions when used in components styled by `styled-components`.
> unselectable: always invoke when interpolated by styled-components

- src/components/SidePanel/SidePanel.js
Alternatively we could check that `onClose` is available [here](https://github.com/aragon/aragon-ui/compare/side-panel-add-default-onclose?expand=1#diff-f5eebddeafb17884215204484008fd4eR90)
> SidePanel: add default onClose

- src/components/Info/IconInfo.js
- src/components/Info/Info.js
Also puts the title's margin to the bottom to be closer to designs.
> Allow IconInfos to break their title and body into multiple lines

- src/components/Countdown/Countdown.js
Once per second wasn’t enough when several countdowns are displayed at the same time.
> Make the countdown refresh at 30 FPS

- gallery/package.json
- gallery/yarn.lock
- package.json
Allows `aragon-ui` to safely use fragments.
I think most of the dependents are already using 16.2.0, so this shouldn't cause any issues.
> React: upgrade to 16.2.0

- gallery/package.json
- gallery/src/pages/PageObserve.js
- gallery/src/render-readme.js
- gallery/src/routes.js
- package.json
- src/index.js
- src/rxjs/README.md
- src/rxjs/index.js
- src/rxjs/observe.js
- src/rxjs/observe.md
- yarn.lock
Adds a convenience HOC for connecting a component to an RxJS observable.
Passes down a transformation of the observable's values as props.
> Add observer HOC for connecting to RxJS

- src/components/Text/Text.js
- src/utils/styles/font.js
This is to allow inheritance from the parent styles.
> Text / font(): do not set defaults if size, weight or color are not set

- src/components/Button/Button.js
Fix the settings buttons in aragon/aragon.
> Button.Anchor: extend its styles with styled()

- gallery/package-lock.json
- gallery/package.json
Depreciates #186.
`Button.Anchor` seems to be properly styled now :).
`markdown-it-anchor` was upgraded from a `npm audit` vulnerability.
> Update gallery dependencies

- devbox/apps/DropDown.js
- src/components/DropDown/DropDown.js
- src/utils/styles/spring.js
Allow nodes in `DropDown items`, so we can use components:
Also:
- Make the transition faster.
- Add a devbox app.
> Dropdown items type

- devbox/.babelrc
- devbox/apps/Button.js
- devbox/index.js
- devbox/package.json
- src/components/Button/Button.js
- src/components/Button/README.md
A smaller button size was needed:
<p align="center">
</p>
This PR introduces a new prop, `size`, that can be set to `normal` (default), `small` or `mini` (the new size).
- `small` is the equivalent to the `compact` prop, and should be used instead.
- `mini` is the new size, which is smaller than the `small` size.
> Button size

- gallery/src/pages/PageEmptyStateCard.js
- src/components/Card/EmptyStateCard.js
- src/components/Card/EmptyStateCard.md
Useful in cases where the entire app might be disabled.
> EmptyStateCard: add prop to disable the action button

- package-lock.json
- package.json
- src/providers/RedrawFromDate/RedrawFromDate.js
- src/utils/date.js
Also pins `date-fns` to `@2.0.0-beta.22` so we don't get unexpected surprises in the future.
> Fix usage of date-fns after switch to Unicode TR35

- devbox/apps/EmptyStateCard.js
- devbox/index.js
- package-lock.json
- package.json
- src/components/Card/EmptyStateCard.js
- src/components/Card/EmptyStateCard.md
- src/components/SidePanel/SidePanel.js
- src/proptypes.js
- src/utils/index.js
- `action` is the new prop that allow to override the button.
- `icon` now accepts elements (passing a component still works but is deprecated).
- `actionButton` still works but is deprecated.
Some warnings will be displayed in the console when deprecated props (or prop types) are used.
This commit also adds:
- Custom prop types in `src/proptypes.js`.
- A `noop()` function in utils.
- lodash-es as a dependency.
- A devbox app for `EmptyStateCard`.
- `log()`, `warn()` and `devOnly` utils.
> EmptyStateCard: deprecates passing components for icon and actionButton

- src/components/Countdown/Countdown.js
While reviewing #225 I ran into this:
> Countdown: fix flickr when counting down

- src/components/AragonApp/AragonApp.js
Prevent strange errors when publicUrl isn't passed.
> Make publicUrl a required prop

- src/providers/PublicUrl/PublicUrl.js
> Fix the “Context.Consumer.Provider is not supported” warning

- src/components/Field/Field.js
Changes the positioning to be based on flex, and uses the `margin: auto` trick to right-align rather than `justify-content: space-between` (makes it easier to add items to the left in the future, e.g. an icon).
> Field: use flex to position required asterisk

- devbox/apps/Timer.js
- devbox/index.js
- src/components/Countdown/Countdown.js
- src/components/Countdown/README.md
- src/components/Timer/README.md
- src/components/Timer/Timer.js
- src/components/index.js
After some chat with @bpierre  on #263, I followed his advice on add a new component called Timer that support both start or end as prop (stopwatch or countdown features). At the same I have kept backwards compat with current Countdown component (that just use Timer internally).
> Add Timer component

- src/components/Button/ButtonBase.js
Super small change from #284 since `cursor` is immediately declared afterwards.
> ButtonBase: remove extra cursor css declaration

- package.json
styled-components is a peer dependency and shouldn’t be installed here. Doing so can be problematic when using `npm link @aragon/ui` in a project, causing two versions of styled-components to be included.
> Remove styled-components from the dev dependencies

- package.json
So we can publish using normal `npm` commands:
```
npm version [major|minor|patch]
npm publish
```
> scripts: replace release:minor by prepublishOnly

- src/components/Button/ButtonIcon.js
To make sure the button is always described with text.
> ButtonIcon: require a label prop

- src/components/Slider/Slider.js
Not sure if `pressed` is somehow used by these two inner components, but as far as I can tell they're not.
React gave an error 🤷‍♂️
> Slider: don't propagate pressed to ActiveBar and Handle

- src/components/NavigationBar/NavigationBar.js
- Ensure the arrow stays during the leave transition of an item (when moving from 2 to 1 items).
- Don’t animate when the component mounts (using the `immediate` prop of `Transition`).
Before:
After:
> NavigationBar: fix transition issues

- README.md
- bin/copy-aragon-ui-assets
- gallery/public/index.html
- gallery/public/manifest.json
- gallery/src/pages/PageColors.js
- gallery/src/pages/PageHome.js
- gallery/src/pages/PageTheme.js
- gallery/src/routes.js
- src/components/Main/README.md
- src/theme/README.md
See [this forum post](https://forum.aragon.org/t/on-aragon-naming/203) for context.
Note: I kept instances of `aragon-ui` in the code, and the color palettes are still named `Aragon UI`. For the color palettes, I don’t think it’s worth breaking the compatibility now, since we are going to do it with the move to Lorikeet anyway.
> Rename Aragon UI to aragonUI

- src/components/IdentityBadge/IdentityBadge.js
Updates rules for text overflow when IdentityBadge has limited space.
> IdentityBadge: add rules for text overflow

- devbox/apps/Popover.js
- src/components/Popover/Popover.js
Fix the super annoying bug where outside clicks were not detected below the popover.
Also move from `Root` to `RootPortal`.
> Popover: fix the click outside detection

- src/components/IdentityBadge/IdentityBadge.js
React was complaining that it was receiving a boolean prop for what should've been a function.
> IdentityBadge: fix props warning message

- devbox/index.js
Fixes 3599f33afac53b6b1d979dbb3c1f2dc3154d5736
Import style changed and `Scratchpad` is no longer defined in `devbox/index.js`
> Devbox fix

- src/components/FocusVisible/FocusVisible.js
This fixes a scenario where:
1. FocusVisible is rendered to a page
2. Something else on the page causes an immediate crash, before FocusVisible's `componentDidMount` can finish running
3. [An ErrorBoundary] catches the error, removing all page contents and replacing them with a stack trace
4. FocusVisible's `componentWillUnmount` fires, but `this._document` is undefined, and it throws an error of its own
5. The ErrorBoundary stack trace gets replaced with the unrelated `FocusVisible` error
[An ErrorBoundary]: https://github.com/AutarkLabs/planning-suite/blob/1971506d838d15bb3423b964d235a18d432565b2/apps/projects/app/components/App/ErrorBoundary.js
> FocusVisible: fix removeEventListener bug

- src/components/BackButton/BackButton.js
- Remove custom icon.
- Align the focus ring on the border.
- Round corners so that Bar doesn’t need `overflow: hidden`.
> BackButton tweaks

- devbox/apps/Info.js
- src/components/Info/Info.js
- src/components/Info/index.js
- “Description” mode (with the grey text, used for radspec).
- Fix title spacing.
- Fix `Info.Permissions` (`warning` rather than `info`).
> Info: description mode + tweaks

- devbox/apps/Button.js
- devbox/apps/Wrappers.js
- src/components/Button/Button.js
- src/components/Header/Header.js
- src/theme/theme-dark.js
- src/theme/theme-light.js
The `display` prop can be used to force the button to behave in certain ways. It replaces `iconOnly`, which is now deprecated.
`display` values:
- `all`: both the icon and the label are displayed.
- `icon`: only the icon gets displayed.
- `label`: only the label gets displayed.
- `auto` (default): like `all` except in some cases (one for now, see below).
If the Button is inside the secondary slot of Header and its display is set to auto, it will alternate between displaying only the label and only the icon, depending on the current layout.
> Button: disabled state + display prop

- devbox/apps/DropDown.js
- src/components/DropDown/DropDown.js
- src/components/DropDown/README.md
- `label` is going to be deprecated and is now renamed to `placeholder`.
- `renderLabel` prop has been added to force display. An example use case is to force display a shorten address instead of the whole address.
- `wide` prop has been added again (was missing since the `newstyle` implementation).
- Update docs.
> DropDown: add placeholder, renderLabel and wide props

- devbox/apps/Card.js
- src/components/CardLayout/CardLayout.js
Still looking for a solution on small layouts, where cards would have a minimum width and a maximum width, and the minimum width would be preferred by the layout algorithm (`minmax()` prefers the max value since `fr` can not be used as a first argument). See https://github.com/w3c/csswg-drafts/issues/2611
Other solutions:
- [`min()`](https://developer.mozilla.org/en-US/docs/Web/CSS/min) or [`clamp()`](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp), which are not supported yet.
- Using Flexbox on the small layout (which would allow `min-width` / `max-width`). Since we are using fixed heights, this might be the easiest solution.
- JS calculations using `Viewport` and `Layout`, passing the calculated dimensions to the children `Card` using context.
> Fix CardLayout on medium and large layouts

- src/utils/web3.js
TrustWallet's repo has the token addresses all lower cased, so we should do the same to `tokenIconUrl()`'s address argument :).
> Web3: always lowercase tokenIconUrl addresses when creating icon URL

- src/components/AddressField/AddressField.js
Doesn't seem like this ref was being used anymore, and it was causing errors since `ButtonIcon` is a function component.
> AddressBook: remove unused ref on ButtonIcon

- src/components/DropDown/DropDown.js
- src/components/Popover/Popover.js
- src/components/Popover/README.md
- Use a border rather than a shadow, for the button and the popup menu.
- Use `theme.surfacePressed` for the pressed state of the button.
- For the selected mode, use `theme.selected` (rather than `theme.accent`).
- Do not scale the popover during the opening transition.
- Popover now passes its props down to the main element.
> Dropdown: newstyle tweaks

- src/components/DropDown/DropDown.js
- src/components/DropDown/README.md
@dizzypaty @owisixseven This is a proposition for a disabled state on DropDown, following the same style we use for disabled buttons (https://github.com/aragon/aragon-ui/pull/432). Please let me know if it works!
> DropDown: disabled mode

- src/components/DataView/DataView.js
- src/components/DataView/README.md
- src/components/DataView/TableView.js
Changes:
- Pass the current mode to the render functions.
- In table mode, let cells use the full width.
> Dataview tweaks

- devbox/apps/Input.js
- src/components/Input/TextInput.js
- src/components/Input/TextInput.md
- Use the new theme colors.
- Use the new text styles.
- No shadow anymore.
- “Selected” (focused) state.
> Input: new style

- src/components/BackButton/BackButton.js
- src/components/Button/Button.js
- src/components/Card/Card.js
- src/components/CardLayout/CardLayout.js
- src/components/Tabs/Tabs.js
- src/utils/inside.js
This is useful to pass some data from the parent component to the consumers.
Consumer:
```jsx
// like before
const insideSomething = useInside('Something')
// pass true as a second parameter to get the optional data
const [insideSomething, somethingData] = useInside('Something', true)
```
Provider:
```jsx
// data can take any value
function Something({ children }) {
return (
<Inside name="Something" data={{ hey: 'hey hey' }}>
{children}
</Inside>
)
}
```
> Inside: allow additional data to be passed

- src/components/DropDown/DropDown.js
- src/components/Popover/Popover.js
- src/components/Popover/README.md
There's a lot of cases where we set toggle functionality on the opener, and this doesn't play nicely with the blur handler on the popper (resulting in difficult-to-fix race conditions with the handlers). For an example, the current [DropDown](https://devbox.dweb.cool/#DropDown) has this problem.
Perhaps this should be protected behind a prop, since it could be a bit surprising if you expected the `onClose()` to always be fired when the Popover closes.
Fixes #477
> Popover: ignore onClose() if focus is on opener

- src/components/Layout/Layout.js
This is an advanced prop that shouldn’t be used by apps. It is used in the onboarding at the moment, which has smaller breakpoints but still use `Split` and similar components.
> Layout breakpoints

- src/components/Input/TextInput.js
It's weird that the focus state would cause an active border if the input is readonly:
> TextInput: use normal border colour when focused in readonly mode

- src/components/Tag/Tag.js
From `3px` to ~`2px`~ `1px`, also making sure it only applies when there are no [descenders](https://en.wikipedia.org/wiki/Descender).
**Edit:** also apply the alignment to the text, not the icon :man_facepalming:
> Tag: tweak the vertical alignment

- src/components/AddressField/AddressField.js
- src/components/DropDown/DropDown.js
- src/components/IdentityBadge/IdentityBadge.js
- src/components/Tag/Tag.js
I've since learned that passing around booleans in declaring styled-components can lead to these errors:
As you said @AquiGorka, it is preferable to use the ternary syntax :).
These components generally don't error, but we may as well use this syntax consistently when defining dynamically styled styled-components.
> Style: prefer ternary declarations in dynamic styled-components

- src/components/DateRange/DateRange.js
Uses `theme.hint` as the colour, and adjusts its text size to be inline with other text inputs.
Previously:
Now:
> DateRange: adjust input field styling

- src/components/Tag/Tag.js
Super minor thing, but it's a bit odd for the component to say "99+" when you give it "99" 😄
> Tag: add '+' to digits only on strict greater than

- src/components/Tabs/TabsFullWidth.js
- src/hooks/useKeyDown.js
-  `TabsFullWidth`: only listen to keydown events when needed.
-  `useKeyDown()`: prevent the event callback to be recreated on every render.
> Keydown fixes

- src/components/BackButton/BackButton.js
The current alignments on larger and smaller screens:
Larger:
Smaller:
> BackButton: adjust padding based on layout, factor in icon padding

- src/components/Box/Box.js
As seen with @dizzypaty, we’ll keep a padding of 2gu all around in full width mode: any extra spacing can be added, but the line height of our text styles is enough in most cases to make it like the design screens.
- ~It is now possible to provide the header and content padding separately, by using an array.~
- Fix the default values (always 2gu in full width).
- ~When padding is 0 or false, the header stop following the content padding (it is still possible to do this by setting it independently using the array).~
- The header stop following the content padding.
- Coding style: remove the internal HeaderContent component.
> Box: update padding behavior

- src/components/FocusVisible/FocusVisible.js
I didn’t realize before how slow `this.setState` can be, even without changing any value. The next step would be to share the same context between all the `FocusVisible` components, so the event is only triggered once.
> FocusVisible: performance fix

- devbox/apps/DataView.js
- src/components/DataView/DataView.js
- src/components/DataView/README.md
- src/components/DataView/TableView.js
- `<Box padding={false}>` => `<Box padding={0}>`
- Skip extra renders in table mode.
- Allow empty header in table mode.
- Allow to disable the pagination.
> DataView improvements

- .eslintrc
- package-lock.json
- package.json
- src/components/AutoComplete/AutoComplete.js
- src/components/ButtonBase/ButtonBase.js
- src/components/DataView/DataView.js
- src/components/DataView/TableView.js
- src/components/DropDown/DropDown.js
- src/components/Info/Info.js
- src/components/Tabs/TabsFullWidth.js
- src/components/ToastHub/ToastHub.js
- src/utils/contains-component.js
Thought we already had this enabled in this repo D:.
Caught a few bugs, but a few of them I'm not 100% sure. @bpierre can you double check? I don't think any of them should cause regressions, since they're mostly based on props that don't change.
> chore: add react-hooks ESLint plugin

- src/components/Button/Button.js
The Button shadow has been [changed](https://github.com/aragon/aragon-ui/commit/62b7a0fa0c7d351264f37829b91eb396340e9a65) at some point, but without adapting its pressed state. This change fixes that.
> Button: fix the shadow of the pressed state

- src/components/Slider/Slider.js
Use the new theme colors + pass the extra props (so we can disable the padding when needed).
The next change will add a “full width” mode to correspond to the new style, where the left side of the handle stops on the left side of the bar, and vice versa.
> Slider: adapt to the new theme

- src/components/Button/Button.js
- src/components/Popover/Popover.js
- Button: `warnOnce()` was used incorrectly
- Popover: try to warn if the `opener` was a `<button>` or `<input>`, and `closeOnOpenerFocus` is set
The Popover's a bit of a PITA. On macOS, both Firefox and Safari don't focus buttons or inputs on click, hence causing `focusevent.relatedTarget` to always be `null`. Users should only be using `closeOnOpenerFocus` if they expect the opener to be focused, so this adds a warning to let users know they should consider using a different focusable element instead.
Note that this check is **not** full-proof, since it's a PITA for us to know if the passed in element is actually focusable (we'd need to implement a tag whitelist, check for `tabIndex`, etc. which probably isn't worth it now).
> Fix some component warnings

- devbox/apps/IdentityBadge.js
- gallery/src/pages/PageTransactionBadge.js
- src/components/AddressField/AddressField.js
- src/components/AddressField/README.md
- src/components/EthIdenticon/README.md
- src/components/IdentityBadge/IdentityBadge.js
- src/components/IdentityBadge/IdentityBadgePopover.js
- src/components/IdentityBadge/PopoverActionType.js
- src/components/IdentityBadge/README.md
- src/components/TokenBadge/TokenBadge.js
- src/components/TokenBadge/TokenBadgePopover.js
- src/components/TransactionBadge/README.md
- src/components/TransactionBadge/TransactionBadge.js
- src/style/text-styles.js
- src/theme/theme-dark.js
- src/theme/theme-light.js
- src/utils/css.js
As seen in [Figma](https://www.figma.com/file/bZ1j7omfhdMCbtFahP3nEJ9B/Client?node-id=598%3A910).
AddressBadge:
IdentityBadge:
TokenBadge:
> Update AddressField, IdentityBadge, TokenBadge, and TransactionBadge to new styles

- devbox/apps/DropDown.js
- src/components/DropDown/DropDown.js
- src/components/IdentityBadge/IdentityBadge.js
-  DropDown: declare `Inside` slots.
- DropDown: stop using closeOnOpenerFocus (removes the warning).
-  IdentityBadge: set `badgeOnly` to `true` when inside of a `DropDown`. 
-  IdentityBadge: use `element="a"` when `badgeOnly=true` (fixes https://github.com/aragon/aragon-ui/issues/448).
> Dropdown + IdentityBadge fixes

- devbox/apps/DropDown.js
- src/components/DropDown/DropDown.js
The second commit (https://github.com/aragon/aragon-ui/commit/688ba3940d7fdc52192613e17261ac07233d7057) is a first attempt to get the `Popover`'s width and use that as the `min-width` for the container, but it only works after the first time the `Popover` appears.
Update: as discussed with @bpierre , followed the approach of having an invisible (out of viewport) content to get the width from.
> Design polish dropdown

- src/components/Field/Field.js
- src/components/Field/README.md
- src/components/Help/Help.js
- Allow children to be a render function that will receive a unique ID, being assigned to the htmlFor prop of the label element (allowing to target a specific element rather than the first one found).
- Declare Inside slots.
- Center using flexbox rather than a custom line-height.
- Add white-space: nowrap.
- Accept React nodes for the label, rather than strings only.
Note: the render prop is a first step that will also be useful for advanced uses, but a solution (to be thought / discussed) will be added later so that `Help` can be used without having to use this feature.
> Integrate Help into Field

- devbox/apps/DropDown.js
- src/components/DropDown/DropDown.js
> DropDown: update caret colour to surfaceIcon

- src/components/Input/TextInput.js
Removes the default `:invalid` styling that some browsers (e.g. Firefox) apply to inputs.
> TextInput: remove :invalid styling on some browsers

- src/components/Modal/Modal.js
Safari doesn't seem to respect the alignment with `grid`, and this for all intents and purposes can use `flex` instead.
See, for example, the share label modal:
> Modal: use display: flex to center modal

- devbox/apps/IdentityBadge.js
- src/components/AddressField/AddressField.js
- src/components/BadgeBase/BadgeBase.js
- src/components/EthIdenticon/EthIdenticon.js
- src/components/IdentityBadge/IdentityBadge.js
Fixes https://github.com/aragon/aragon-ui/issues/338
- EthIdenticon: fix border-radius on Chrome.
- AddressField: use a `<a>` when read only.
> EthIdenticon + BadgeBase fixes

- src/components/AddressField/AddressField.js
cc @AquiGorka @bpierre.
This regression was caused by `TextInput`'s additional wrapper `div` when using adornments. I couldn't figure out a way to get it to only grow to the remaining width of the flex container, so reverted to the previous layout's trick of using an absolute position for the icon and padding for the text input.
> AddressBadge: fix overflow on small screens

- src/components/AppBadge/AppBadge.js
The `appAddress` is only used in the AppBadge's popover, and this is disabled in `badgeOnly` mode.
> AppBadge: avoid appAddress warning if badgeOnly is set

- rollup.config.js
The `filesize` plugin seems to have started failing when trying to generate the brotli file size.
> Build: disable analyzing brotli file size

- src/components/Modal/Modal.js
Essentially reverts https://github.com/aragon/aragon-ui/pull/582, but changes the `align-items` to `align-content` as a way of getting the centering to work on Safari.
> Modal: fix overflowing height and centering on Safari

- src/components/ToastHub/ToastHub.js
Ref: https://github.com/aragonone/product/issues/196
Fixes issue in client where ToastHub was rendering the Toasts at a lower level down the tree from some overlays.
> ToastList: wrap in root portal

- src/components/DropDown/DropDown.js
- src/components/Popover/Popover.js
These changes fix the following issues (from https://github.com/aragonone/product/issues/196)
- Finance Mobile
- Fix DropDown in new deposit
- New Transfer Deposit on Mobile: DropDown Popover does not scroll so it is not possible to select one of the first tokens nor close the list options without choosing one.
> Dropdown & Popover fixes for dimensions and scrolling

- src/components/Split/Split.js
Usage:
```jsx
<Split
invert="horizontal"
primary={
<div>
On large viewports, this will get displayed
on the right side rather than the left.
</div>
}
secondary={
<div>
On large viewports, this will get displayed
on the left side rather than the right.
</div>
}
/>
```
Note: “left” and “right” will mean the opposite when right to left support will be added to aragonUI.
```jsx
<Split
invert="vertical"
primary={
<div>
On small viewports, this will get displayed second.
</div>
}
secondary={
<div>
On small viewports, this will get displayed first.
</div>
}
/>
```
/cc @onbjerg @deamme
> Split: allow to invert (visually) the two slots

- src/components/AutoComplete/AutoComplete.js
- src/components/AutoComplete/README.md
When we have more items on `AutoComplete` the wrapper expands with the items. Adding max-height fixes this. Hope this is a good PR for the system. Here is the screenshot of the UI before and after style changes:
- Before: 
- After
> AutoComplete doc: suggest to limit the number of items

- devbox/apps/TokenBadge.js
- src/utils/web3.js
Fixes https://github.com/aragon/aragon-ui/issues/629 and https://github.com/aragon/aragon-ui/issues/624
I went for the `0x000…` solution for now, I think we could do that for now and support other chains whenever it will become needed.
> tokenIconUrl(): support ETH + update source

- src/components/TextCopy/TextCopy.js
So that it can be extended easily.
> TextCopy: set the width on the main container

- package.json
- src/utils/web3.js
The format has recently changed on the [source repository](https://github.com/trustwallet/assets/pull/502), and token icons can now only be accessed through checksum addresses.
web3-utils [is huge](https://bundlephobia.com/result?p=web3-utils@1.2.2), so I copied the `toChecksumAddress()` function there and made it use [js-sha3](https://github.com/emn178/js-sha3), which is [quite small](https://bundlephobia.com/result?p=js-sha3@0.8.0) and [used by ethers.js](https://github.com/ethers-io/ethers.js/blob/76a8e503dd47b8da1961fb85a6ca28d007f49585/utils/keccak256.js), so it seems like a reasonable choice for the time being.
@sohkai let me know what you think! Another approach would be to only support checksum addresses for `TokenBadge`.
> tokenIconUrl(): new source format (checksum addresses)

- gallery/src/pages/PageDropDown.js
- Set `container` as `false` on the attached Demo component on the PageDropdown component.
- Remove the `Container` component
- Remove the extra div with css for centering
- Pass the `selected` prop to the dropdown for displaying an item.
- Set the default state of the demo to -1 to display the default placeholder.
This PR closes #670
> Gallery dropdown content bug fix & demo enhancement

- gallery/src/pages/PageRootPortal.js
- Changed size prop from "compact" (deprecated) to "small". This was making the page not render due to an uncaught error.
This PR closes #674
> Solve RootPortal page bug

- src/components/Button/Button.js
- src/theme/theme-dark.js
- src/theme/theme-light.js
- Button: change the gradient orientation.
- Change the accent gradient to improve the contrast.
- In dark mode, change the `selected` color .
- In dark mode, make the `overlay` darker.
Before:<br><img width=60% src=https://user-images.githubusercontent.com/36158/69894414-3ea1b680-12fe-11ea-8762-de8fe67c6345.png>
After:<br><img width=60% src=https://user-images.githubusercontent.com/36158/69894407-2e89d700-12fe-11ea-9eff-67a2245d4924.png>
> Update colors (dark theme preparation)

- src/theme/Theme.js
Even if the passed theme has the same name than an embedded theme, we now always override it with the passed one.
See discussion https://github.com/aragon/aragon-ui/pull/685/files#r359157304
> Theme: always extend the base theme

- src/components/CardLayout/CardLayout.js
- Adds the ability to set `"auto"` on the `rowHeight` prop, handling the CSS properly instead of setting auto values in a hacky way for the card.
Closes #635 , discussion [here.](https://github.com/aragon/aragon-ui/commit/b2d1da7f7cce7ed3dd7cf843296c41ac13f67100#r35625086)
> Handle auto value through the rowHeight prop on the CardLayout component

- src/components/AutoComplete/AutoComplete.js
- src/components/AutoComplete/AutoCompleteSelected.js
This PR updates AutoComplete to support dark mode. Additionally, AutoCompleteSelected has been updated to pass `itenButtonStyles` props to the AutoComplete component.
Before:
After:
> Dark mode support for AutoComplete

- src/components/Popover/Popover.js
- src/components/Popover/README.md
I’m wondering if a more transparent approach could be to wait for the next tick, then focus again if `visible` is still `true`.
> Popover: reject closing

- src/components/Timer/README.md
- src/components/Timer/Timer.js
- src/components/index.js
Adding this new prop so we can choose to not show the clock icon.
This will be useful for the court dashboard. See https://github.com/aragon/court-dashboard/pull/227#discussion_r389214082
> Timer show icon prop

- babel-plugin-aragon-ui/.babelrc
- babel-plugin-aragon-ui/.gitignore
- babel-plugin-aragon-ui/README.md
- babel-plugin-aragon-ui/package.json
- babel-plugin-aragon-ui/src/gu.js
- babel-plugin-aragon-ui/src/index.js
- babel-plugin-aragon-ui/src/utils/detectors.js
See discussion: https://github.com/aragon/aragon-ui/issues/333
Plugin greatly inspired from [babel-plugin-styled-components](https://github.com/styled-components/babel-plugin-styled-components), and made to work with it.
Transforms this:
```jsx
<div
css={`
width: 4gu;
height: 4gu;
`}
/>
```
Into this:
```jsx
<div
css={`
width: 32px;
height: 32px;
`}
/>
```
- Adds the `gu` unit to styled component’s CSS blocks (in normal styled
components, in the `css` prop, or using the `css` helper).
In your .babelrc, declare this plugin before styled-components:
```json
{
"plugins": [
"@aragon/babel-plugin-aragon-ui",
"styled-components"
]
}
```
- Support for text styles: `-ui-text-style: title1`
- Support for theme values: `-ui-theme(surfaceContent)`
Note: both are using the [CSS syntax for proprietary …
> Add a babel plugin to handle the gu unit

- package.json
Update prettier version to 1.19.0 since there is there are differences on the column limit between the versions
> Packages: Prettier version upgrade

- src/components/Timer/README.md
> Timer: documentation about maxUnits prop

- src/components/Slider/Slider.js
> Slider: Add onTouchStart to slider circle

- src/hooks/useKeyDown.js
In cases where there are multiple keycodes listened to, this allows the handler to know which key was pressed and how to handle it.
> useKeyDown: propagate event's keycode to handler

- devbox/apps/TransactionProgress.js
- src/components/Tabs/TabBarLegacy.js
- src/theme-legacy/palettes.js
- src/theme/Theme.js
- src/theme/theme-dark.js
- src/theme/theme-light.js
Fixes https://github.com/aragon/aragon-ui/issues/476
Warn in the following cases:
- Deprecated colors.
- Unknown colors.
- Invalid theme.
Also:
- Move TabBarLegacy to `useTheme()`.
- Move deprecated colors in `Theme.js`, rather than in every theme.
> Theme: warn when invalid colors are being accessed

- docs/GettingStarted.md
On GettingStarted.md, there was a sample code block that was using `<Tag>`component, but it wasn't being imported.
> Docs: fix sample code, component import was missing

- src/components/Radio/RadioListItem.js
> re-align RadioListItem button to top of component

- gallery/src/pages/PageToastHub.js
- src/components/Radio/RadioListItem.js
- src/components/ToastHub/ToastHub.js
Also:
- Move to Flexbox.
- Remove unnecessary `<ToastHub>` on the gallery page.
> Toast: fix alignment

- src/theme/theme-dark.js
I found `positiveSurfaceContent` to lack contrast in the dark theme. It might just be the context i've been using it but even still it felt on the low side.
> Dark theme: Increase positive content contrast

- README.md
The [old link](https://1hive.org/projects/dandelion-orgs/dandelion-overview/) was giving this 404 response:
> docs: update 1hive broken link

- src/components/EscapeOutside/EscapeOutside.js
- src/components/EscapeOutside/README.md
- src/components/Modal/Modal.js
resolves https://github.com/aragon/aragon-ui/issues/790
I've added a `useCapture` prop to `EscapeOutside` to allow us to optionally change the event propagation from bubbling to capture, this allows us to reverse execution order on the events, this is especially important for the `Modal` so that outside interaction checks can happen before others potentially affect render state.
More info: https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Event_bubbling_and_capture
> Modal: Prevent EscapeOutside from causing problems with internal interactions

- src/components/TokenAmount/TokenAmount.js
I ran into a problem where expandable elements such as those on `DataView` and `Accordion` were measuring height dimensions incorrectly because `TokenAmount` wasn't mounted prior and hadn't loaded token images to render space.
A solution is to always provide the dimensions and a placeholder during load, this also stops content hopping around.
This does present the question of whether a placeholder being present when a fake token is used is acceptable. I think we should optimise for the common use case (a token address has an asset) and if we need to we can give the option to hide the token graphic via a flag in the future.
> TokenAmount: Hold token space during image load

- src/components/DataView/TableView.js
Spring seems to have some internal logic for animating to `auto` which is nice and means the expanded node will keep flow on resize and when sorting entries.
> DataView: Prevent expansion close on re-render

- .github/auto_assign.yml
- .github/stale.yml
Removing the issue stale bot, since we usually do a pretty good job of closing them when they become irrelevant or fixed.
> chore: update stale bot

- src/components/Input/Checkbox.js
Given that the `<Checkbox/>` component renders a `<span>` element with a `<button>` element as a parent, by default, the `Enter` key triggers the `keypress` event. 
This PR disables the default action on the `keypress` event that triggers the `click` event later on.
**Note**: the checkbox can still be checked with the `Space` key thanks to the `role` attribute.
Resolves #626
> Checkbox [fix]: prevent default onkeypress action
